#! /bin/bash

rm count.txt
for file in *
do
	if [[ -f $file ]]; then
		du -s $file >> count.txt
	fi

done
for file in *
do
	if [[ -d $file ]]; then
		du -s $file >> count.txt
	fi
done

cat count.txt | awk '{ sum+=$1} END {print sum/1000000}'
